---
format: html
editor: visual
toc: false
---

### WiDS Tucson Conference

This Tucson WIDS meeting aims to further build the community around women in Data Science. The meeting provides a forum for women to share technical information about their projects with each other, and community members; to explore innovative topics emerging in the software and data infrastructure communities; to discuss and learn about best practices across projects; and to stimulate new ideas of achieving software and data sustainability and new collaborations.

Women in the data science community are invited to present talks and posters on their projects. Anyone who is interested in attending the meeting is welcome and encouraged to do so.

There is no registration fee, but participants need to register by **April 20th, 2023 at 12pm MST** to allow for planning logistics. This meeting is virtual and will be hosted on Zoom. Participants are encouraged to move between Zoom meetings to maximize their own experience.

Find past meeting agendas in [Meeting Archive](https://wids-tucson.github.io/archive.html).
