---
toc: false
format: 
  html: 
    tbl-colwidths: [10,20,50,40]
    max-width: 40em
editor: visual
---

::: callout-important
#### [Register](https://www.eventbrite.com/e/wids-tucson-2023-tickets-580664311587)

#### 🗓 Thursday--Friday, April 20th -- 21st, 2023

#### ⏰ 8:30am-5:30pm MST
:::

#### April 20 (Thursday) -- Schedule of Sessions:

+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| Time          | Session                    | Title/Location                                                                                          | Speaker(s)                                                       |
+===============+============================+=========================================================================================================+==================================================================+
| 8:30a-9:00a   | Opening                    | Light Breakfast                                                                                         |                                                                  |
|               |                            |                                                                                                         |                                                                  |
|               |                            | *Student Union -- Kachina*                                                                              |                                                                  |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 9:00a-9:45a   | Keynote                    | Using Data to Deliver Equitable Outcomes for the American People                                        | Denice Ross                                                      |
|               |                            |                                                                                                         |                                                                  |
|               |                            | *Student Union -- Kachina (also online in* also in [room A](https://arizona.zoom.us/j/88420856384))     | U.S. Chief Data Scientist                                        |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 9:50a-10:05a  | Morning Talks              | Mood and Language: Insights from Brain Data                                                             | Vicky Lai                                                        |
|               |                            |                                                                                                         |                                                                  |
|               |                            | *Student Union -- Kachina (also online in* also in [room A](https://arizona.zoom.us/j/88420856384))     | Asst Prof, Psychology                                            |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 10:10a-10:25a | Morning Talks              | Data mining and linguistics                                                                             | Heather Froehlich                                                |
|               |                            |                                                                                                         |                                                                  |
|               |                            | *Student Union -- Kachina (also online in* also in [room A](https://arizona.zoom.us/j/88420856384))     | UA Libraries                                                     |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 10:30a-10:45a | Concurrent Morning Talks   | Indigenous Data Governance                                                                              | Riley Taitingfong                                                |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room A](https://arizona.zoom.us/j/88420856384))                                                | Postdoc, NNI/Udal                                                |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 10:30a-10:45a | Concurrent Morning Talks   | Open Science principles applied to the study of the gut microbiome, and inflammation after brain injury | Luisa Maria Rojas                                                |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room B](https://arizona.zoom.us/s/81289501438))                                                | PhD candidate, University of Arizona College of Medicine-Phoenix |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 10:50a-11:15a | Morning Data Blitz         | Online ([room A](https://arizona.zoom.us/j/88420856384))                                                | Valeria Pfeifer                                                  |
|               |                            |                                                                                                         |                                                                  |
|               |                            |                                                                                                         | Kathleen J. Kennedy                                              |
|               |                            |                                                                                                         |                                                                  |
|               |                            |                                                                                                         | Simona Merlini                                                   |
|               |                            |                                                                                                         |                                                                  |
|               |                            |                                                                                                         | Kapua Ioane                                                      |
|               |                            |                                                                                                         |                                                                  |
|               |                            |                                                                                                         | Bailie Wynbelt                                                   |
|               |                            |                                                                                                         |                                                                  |
|               |                            |                                                                                                         | Nimet Beyza Bozdag                                               |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 11:20a-12:20p | Morning Panels             | Machine Learning vs. Statistics                                                                         |                                                                  |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room A](https://arizona.zoom.us/j/88420856384))                                                |                                                                  |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 11:20a-12:20p | Morning Panels             | Data Science Training                                                                                   |                                                                  |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room B](https://arizona.zoom.us/s/81289501438))                                                |                                                                  |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 12:20p-1:00p  | Break                      |                                                                                                         |                                                                  |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 1:00p-1:15p   | Concurrent Afternoon Talks | Collaboration Networks and Career Trajectories                                                          | Sarah Bratt                                                      |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room A](https://arizona.zoom.us/j/88420856384))                                                | Asst Prof, iSchool                                               |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 1:00p-1:15p   | Concurrent Afternoon Talks | Multi-functional, multi-millennial data series from tree-rings                                          | Charlotte Pearson                                                |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room B](https://arizona.zoom.us/s/81289501438))                                                | Associate Professor, Tree Lab                                    |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 1:25p-1:40p   | Concurrent Afternoon Talks | Reading Between the Radiocarbon Lines - Determining the Ages of Archeological Sites                     | Meaghan Wetherell                                                |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room A](https://arizona.zoom.us/j/88420856384))                                                | Asst Prof Practice, iSchool                                      |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 1:25p-1:40p   | Concurrent Afternoon Talks | Theory and Application of BART: A Bayesian Machine Learning Model                                       | Danielle Van Boxel                                               |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Online ([room B](https://arizona.zoom.us/s/81289501438))                                                | PhD Student, Applied Math/DataViz                                |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 1:40p-2:00p   | Closing                    | Closing ([room A](https://arizona.zoom.us/j/88420856384))                                               |                                                                  |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+
| 4:30p         | Social                     | Happy Hour                                                                                              |                                                                  |
|               |                            |                                                                                                         |                                                                  |
|               |                            | Snakes & Lattes (988 E University Blvd, Tucson, AZ 85719)                                               |                                                                  |
+---------------+----------------------------+---------------------------------------------------------------------------------------------------------+------------------------------------------------------------------+

#### April 21 (Friday)

+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
| 1:30p - 2:30p | Talk              | Designing to Disrupt: Creating space for the work that matters to you                                                                                                                                                                                     | Dr. Nicki Washington |
|               |                   |                                                                                                                                                                                                                                                           |                      |
|               | Gould-Simpson 906 | As technology becomes more pervasive, it's important to understand how identity impacts and is impacted by it. This talk discusses the importance of becoming disruptors in not only technology development, but also academic/professional environments. | Duke University      |
+---------------+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+
