---
toc: false
format: 
  html: 
    tbl-colwidths: [10,20,50,40]
    max-width: 40em
editor: visual
---

::: callout-important
#### [Register](https://forms.gle/ttzf3MyogJuCNAeD9){target="_blank"}

#### 🗓 Friday March 29, 2024

#### ⏰ 8:30am-5:30pm MST
:::

The entire conference will be virtual friendly.

If you join us in person or for the watch party, we will be located in **Main Library Room B252/254** ([map](https://lib.arizona.edu/sites/default/files/main-floor2.pdf)). We will also be providing lunch, so be on the lookout for a sign-up form!

::: columns
::: {.column width="15%"}
:::

::: {.column width="30%"}
*Room A*

-   In person: room B254

-   Zoom link:
:::

::: {.column width="10%"}
:::

::: {.column width="30%"}
*Room B*

-   In person: room B252

-   Zoom link:
:::
:::

+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| Time              | Session                             | Title                                                                                      | Speaker(s)                                           | Location                                                  |
+===================+=====================================+============================================================================================+======================================================+===========================================================+
| 8:30am - 9:00am   | Opening                             | WiDS Worldwide official video                                                              | \-                                                   | In person & online                                        |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 9:00am - 9:45am   | Morning Keynote                     | TBD                                                                                        | Angela Cruze                                         | In person & online                                        |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 9:50am - 10:05am  | Morning Talks                       | Community-driven web interface development for enabling global scientific sample discovery | Natalie Raia                                         | In person & online                                        |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 10:10am - 10:25am | Morning Talks                       | Hate speech and counter speech detection: Conversational context does matter               | Xinchen Yu                                           | In person & online                                        |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 10:30am - 10:45am | Concurrent Morning Talks            | Are Women’s Works and Claims Received with More Uncertainty?                               | Jina Lee                                             | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 10:30am - 10:45am | Concurrent Morning Talks            | Educators in Data Science Fellowship Opportunities                                         | Angela Marquez                                       | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room B*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 10:50am - 11:15am | Morning Data Blitz                  | TBD                                                                                        | TBD                                                  | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 11:20am - 12:20pm | Morning Panels                      | Interdisciplinary Data Science: A Roundtable Discussion\*                                  | Alex Labenz, Bailie Wynbelt, Anna Leach, Karen Barto | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 12:20pm - 12:30pm | Break                               | \-                                                                                         | \-                                                   |                                                           |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 12:30pm - 1:00pm  | Lunch + Birds of a Feather sessions | topics to be announced soon!                                                               | \-                                                   | Online & in person                                        |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Rooms A & B*                                             |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 1:00pm - 1:45pm   | Afternoon Keynote                   | Recognizing Implicit Emotions in Text Data                                                 | Ellen Riloff                                         | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 1:50pm - 2:05pm   | Concurrent Afternoon Talks          | The Many Aspects of Data Science - Medical Informatics Examples                            | Gondy Leroy                                          | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 1:50pm - 2:05pm   | Concurrent Afternoon Talks          | Are women really (not) more talkative than men?                                            | Valeria Pfeifer                                      | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room B*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 2:10pm - 2:25pm   | Concurrent Afternoon Talks          | Data Rescue: Saving Ecological Data From Extinction                                        | Ellen Bledsoe                                        | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 2:10pm - 2:25pm   | Concurrent Afternoon Talks          | Navigating the Future of Cybersecurity in the Age of Cloud, Containers, and AI             | Dalal Alharthi                                       | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room B*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 2:30pm - 2:55pm   | Afternoon Data Blitz                | TBD                                                                                        | TBD                                                  | Online (optional in-person watch party)                   |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 2:55pm - 3:20pm   | Closing Discussion                  | How to continue to build Tucson WiDS community!                                            | \-                                                   | Online & in person                                        |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | *Room A*                                                  |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+
| 4:00pm - 6:00pm   | Social                              | \-                                                                                         | \-                                                   | Snakes & Lattes (988 E University Blvd, Tucson, AZ 85719) |
|                   |                                     |                                                                                            |                                                      |                                                           |
|                   |                                     |                                                                                            |                                                      | [map](https://maps.app.goo.gl/KHQFumtjxDZKTLQ97)          |
+-------------------+-------------------------------------+--------------------------------------------------------------------------------------------+------------------------------------------------------+-----------------------------------------------------------+

\***Morning panel theme**: Entering data science from a non-STEM background or transitioning into a new discipline after having been in a STEM field
