---
toc: false
format: 
  html: 
    tbl-colwidths: [10,20,50,40]
    max-width: 40em
editor: visual
---

# WiDS Tucson presents:  {.center}

::: center
## Living in the ever changing landscape of data
:::

with a [keynote] address by Catherine D'Ignazio,

and learning tracks that include:

1.  *Technical and tools*: technical sessions (talks + hands-on workshops / teaching sessions) that are focused on tools, techniques, datasets, and problem solving approaches

2.  *Professional, leadership, and networking*: talks on professional growth & development, career paths, building community & networks, and advice for building skills for an uncertain future

::: callout-important
#### Registration coming soon!

#### 🗓 Friday March 28, 2025

#### ⏰ TBD
:::

### Keynote Speaker

[Catherine D’Ignazio](https://kanarinka.com/) is an Associate Professor of Urban Science and Planning in the Department of Urban Studies and Planning at MIT. She is also Director of the[ Data + Feminism Lab](http://dataplusfeminism.mit.edu/) which uses data and computational methods to work towards gender and racial justice. D’Ignazio is a scholar, artist/designer and hacker mama who focuses on feminist technology, data literacy and civic engagement. Her 2020 book from MIT Press,[ Data Feminism](https://bookbook.pubpub.org/data-feminism), co-authored with Lauren Klein, charts a course for more ethical and empowering data science practices. Since 2019, she has co-organized[ Data Against Feminicide](http://datoscontrafeminicidio.net/), a participatory action-research-design project, with Isadora Cruxên, Silvana Fumega and Helena Suárez Val, which includes co-designed AI tools for human rights data activists. Her 2024 book,[ Counting Feminicide: Data Feminism in Action](https://mitpress.mit.edu/9780262048873/counting-feminicide/) (MIT Press) is an extended case study about grassroots data activism to end gender-related violence. D'Ignazio's research at the intersection of technology, design & social justice has been published in the Big Data & Society, the Journal of Community Informatics, and the proceedings of ACM SIGCHI and ACM FAccT. Her art and design projects have won awards from the Tanne Foundation, Turbulence.org and the Knight Foundation and exhibited at the Venice Biennial and the ICA Boston.
