---
title: "2024 Speakers"
format: html
editor: visual
toc: false
---

# Keynote speakers

------------------------------------------------------------------------

#### Ellen Riloff

Professor and Department Head, Computer Science, University of Arizona

#### Angela Cruze

Director of Programming & Operations, Institute for Computation & Data-Enabled Insight, University of Arizona

# Invited speakers

------------------------------------------------------------------------

#### Xinchen Yu

I am an Assistant Professor of Practice in the Computer Science Department at University of Arizona. I received my Ph.D. from University of North Texas in 2023. My research interests lie at the intersection of natural language processing (NLP) and Computational Social Science (CSS). Specifically, I am passionate about utilizing data-driven methods to support online safety and facilitate communications between people.

#### Valeria Pfeifer

I am a postdoctoral researcher studying language using a neuro-cognitive and a phenomenological lens. Specifically, my research aims to understand what language reveals about a speaker beyond its linguistic content, for example emotional or cognitive states. I currently work at the Naturalistic Observation of Social Interaction Lab in the Psychology Department at the University of Arizona, where I also obtained a Ph.D. in Psychology in 2022. Beyond research, I am involved in the Research Bazaar data science community.

#### Ellen Bledsoe

Ellen Bledsoe is an Assistant Professor of Practice in the School of Natural Resources and the Environment at the University of Arizona. She teaches primarily undergraduate courses with data science components (data management in spreadsheet, introduction to R, etc.). Ellen is trained as a community ecologist; during her PhD, she studied long-term dynamics of desert rodents in the Chiricahuas and is happy she has landed back in the Arizona desert.

#### Gondy Leroy

Gondy Leroy is Professor in MIS and Associate Dean for Research at the University of Arizona. Before coming to Eller in 2013, she joined Claremont Graduate University after earning her PhD in Management Information Systems from the University of Arizona in 2003. Her research focuses on natural language processing and machine learning with a practical and positive impact. Current example projects are the creation of an online editor for text and audio simplification and automated annotation of behaviors matching diagnostic criteria of autism spectrum disorders (ASD) in EHR. She has won grants from NIH, AHRQ, NSF, Microsoft Research, and several foundations totaling \$5.7M as principal investigator, and another \$2.1M as co-investigator. She earned a BS/MS degree (1996) in experimental psychology from the University of Leuven (1996) in Belgium and a MS (1999) and PhD (2003) degree in management information systems from the University of Arizona. In addition to her research, she wrote the book “Designing User Studies in Informatics” (Springer, 2011) and is an active contributor to increasing diversity and inclusion, e.g., through her “Tomorrow’s Leaders Equipped for Diversity” program at the Eller College of Management.

#### Jina Lee

Jina Lee is a Ph.D. Candidate in Sociology at the University of Arizona. Her research program explores the processes and consequences of valuation: the social process through which importance, worth, or significance is assigned to ideas, practices, or contributions. She primarily focuses on which novel discoveries are viewed as important in science, and how this affects scientific progress. She also examines how gender and race shape decisions of what is important, and how this reinforces existing inequality. Her work contributes to the sociology of science and knowledge, gender, medical sociology, and culture. She employs diverse methods such as computational text analysis and survey-based experiments. Her research is published in American Sociological Review, Socius, and Journal of Social Entrepreneurship.

#### Natalie Raia

Natalie Raia is a Postdoctoral Research Associate in the School of Information at the University of Arizona. A geoscientist by training, her current research focuses on studying physical sample collection and reuse practices of scientists in order to inform improvements to the functionality and usability of next-gen digital sample and data repositories. She also conducts mapping of data systems to support increased interoperability and participates in community engagement and guideline development to enable scientists to make their data more discoverable and reusable. Natalie holds a Ph.D. in geology from the University of Minnesota, and a B.S. in geology and B.A. in Plan II Liberal Arts Honors from the University of Texas at Austin.

#### Dalal Alharthi

Dr. Dalal Alharthi is an Assistant Professor in the Cyber, Intelligence, and Information Operations (CIIO) Department at the University of Arizona. Holding a Ph.D. in Computer Science from the University of California, Irvine, and dual master’s degrees, her academic credentials are as broad as they are deep. Before transitioning to academia, Dr. Alharthi gained valuable hands-on experience in the cybersecurity industry through roles such as a Cloud Security Engineer at Farmers Insurance, a Resident Engineer at Palo Alto Networks, and a Prisma Cloud Consultant at Dell. Her professional journey has spanned several countries, providing her with a rich perspective from working in both Eastern and Western contexts. This diverse experience, combined with her significant contributions to both industry and academia, has equipped her with a unique insight into the field of cybersecurity. Dr. Alharthi is dedicated to sharing her knowledge, focusing on the development and education of the next generation of cybersecurity professionals in this rapidly changing discipline, while also actively promoting diversity and inclusion to bridge the gender gap in STEM fields and create a more equitable and vibrant scientific community.

#### Angela Marquez

Yá'át'ééh! Shí éí Angela Marquez yíníshyé'. Táchii’nii nishłį́ áádóó Tł’ááshchí’í ’éí bá shíshchíín. Kinyaa’áanii ’éí dashicheii áádóó Tábąąhí ’éí dashinálí. My name is Angela Marquez and I am Diné, indigenous to Leupp, AZ on the Navajo Nation. I have learned from my family the importance of considering relational accountability and in what ways we are supporting our community. For me, education with the focus on Native Nation building helps me consider the ethical implications of our actions and how they affect our way of life, our foods, our air, our lands, our water, our mother, earth; in an effort to maintain hózhó, or harmony with our world and each other. My current work with the Data Sciences Academy connects me to educators across the state of Arizona and allows me to find ways to support our educators in data science education. Let's connect! I'd love to chat more. I can be reached at ayazzie@arizona.edu. Ahéhee! Talk soon!

# Panelists

------------------------------------------------------------------------

#### Alex Labenz

M.A. Student, Division for Late Medieval and Reformation Studies, University of Arizona

#### Bailie Wynbelt

B.S. Student, Information Science with an emphasis in Data Science, University of Arizona

#### Anna Leach

PhD Student, School of Information with a minor in Teaching, Learning and Sociocultural studies, University of Arizona

#### Karen Barto

Writing Specialist, Writing Skills Improvement Program, College of Humanities, University of Arizona
