---
title: "2023 Speakers"
format: html
editor: visual
toc: false
---

# Denice Ross

April 20, 9am -- Keynote, *Student Union -- Kachina (also online in* also in [room A](https://arizona.zoom.us/j/88420856384))

Denice Ross is the second person and first woman to serve as the Chief Data Scientist of the United States. Through this role in the White House Office of Science and Technology, Denice leads the Biden-Harris Administration equitable data work. She also served in the Obama-Biden Administration where she co-founded the White House Police Data Initiative to increase transparency and accountability. Before moving to DC, Denice established the City of New Orleans' first open data initiative and co-directed a non-profit data intermediary that became the go-to resource for data to inform an equitable recovery after Hurricane Katrina. Denice holds a Bachelor of Science in Biology from the University of Arizona (Class of '94) and a masters degree in Energy Policy & Climate from Johns Hopkins University. While at the University of Arizona, Denice was active in the Undergraduate Biology Research Program.

# Vicky Lai

April 20, 9:50am -- Morning Talk, *Student Union -- Kachina (also online in* also in [room A](https://arizona.zoom.us/j/88420856384))

Dr. Lai is faculty in Psychology, Cognitive Science at the University of Arizona. She directs the Cognitive Neuroscience of Language Laboratory (https://neurolang.lab.arizona.edu/), where lab members use behavioral, electrophysiological, and imaging measures to study figurative language, emotion and language, and language and thought. Dr. Lai is an elected fellow in the Psychonomic Society. In 2022 she received two National Science Foundation grants: "Learning science concepts through metaphor comprehension, production, and conversation" and "Effects of context on emotional word processing in healthy younger and older adults".

# Heather Froehlich

April 20, 10:10am -- Morning Talk, *Student Union -- Kachina (also online in* also in [room A](https://arizona.zoom.us/j/88420856384))

Heather Froehlich is the new digital scholarship specialist at the University of Arizona Libraries. She supports digital scholarship activities across the University of Arizona, with a particular focus on text and data mining. Heather's training is primarily in corpus stylistics, historical sociolinguistics, literary linguistics, and digital humanities. She's especially interested in ways one can use off-the-shelf software and platforms as a route into text analysis and other digital methods.

# Riley Taitingfong

April 20, 10:30am -- Concurent Morning Talk, Online ([room A](https://arizona.zoom.us/j/88420856384))

Riley Taitingfong (CHamoru) is a researcher and educator working on issues of environmental justice, Indigenous self-determination, emerging technologies, and community engagement. She completed her PhD in Communication at the University of California San Diego, where her project focused on Indigenous governance of genetic engineering technologies known as gene drives. Riley is currently a postdoctoral researcher with Udall and the Native Nations Institute, working on the implementation of CARE Principles of Indigenous Data Governance within data repositories. As a CHamoru researcher, Riley is committed to building cross-movement solidarity among Indigenous communities from Oceania to Turtle Island.

# Luisa Rojas

April 20, 10:30am -- Concurrent Morning Talk, Online ([room A](https://arizona.zoom.us/j/88420856384))

Luisa Rojas is a Ph.D. candidate in clinical translation sciences. Luisa began the CTS Ph.D. program at the College of Medicine-Phoenix in Fall 2018 with a Fulbright Fellowship from Colombia. She has undertaken a translational dissertation to use the fecal microbiome as pharmacodynamic outcome of therapeutic interventions for TBI in mice and people. She has contributed to a number of diverse research projects, which include histology, data sciences, and social impact.

# Salena Torres Ashton

April 20, 11:20am -- Morning Panel, Machine Learning vs. Statistics, Online ([room A](https://arizona.zoom.us/j/88420856384))

Salena Torres Ashton is a third-year PhD student in the School of Information and a graduate associate researcher for the ToMCAT grant. Her research interests include knowledge representation, machine learning, causal inference, and artificial intelligence. Prior to pursuing her graduate studies, Salena spent over 20 years working as a professional social/ family historian and a secondary school math instructor. Salena enjoys solo backpacking and sustainable gardening.

# Hong Cui

April 20, 11:20am -- Morning Panel, Machine Learning vs. Statistics, Online ([room A](https://arizona.zoom.us/j/88420856384))

Dr. Hong Cui is a Professor in the iSchool/School of Information at the University of Arizona. Through several NSF-sponsored projects, she has led the development and evaluation of machine learning and language processing tools to convert legacy biodiversity descriptions into new Semantic Web formats and to create user-friendly ontologies. Her more recent data science projects include the use of ML methods in a large-scale data integration effort, predicting leading indicators of worker injuries, and analyzing complicated color traits in biodiversity.

# Jessica Guo

April 20, 11:20am -- Morning Panel, Data Science Training, Online ([room B](https://arizona.zoom.us/s/81289501438))

Jessica Guo is a plant ecophysiologist and data scientist who studies plant-environment interactions under extreme climate, focusing on drylands subject to potentially lethal combinations of heat and drought. She is excited to learn and teach reproducible workflows, interactive visualizations, and hierarchical Bayesian models as a member of CCT Data Science at the University of Arizona. \

# Laurie Sheldon

April 20, 11:20am -- Morning Panel, Data Science Training, Online ([room B](https://arizona.zoom.us/s/81289501438))

Laurie Sheldon works as a researcher in the Center for Assessment, Teaching, and Technology at the University of Arizona where she received her Ph.D. degree in Teaching, Learning, and Sociocultural Studies with a minor in Cognitive Science. Her research centers on digital literacies from a sociocultural perspective. She focuses on data literacies, more specifically individuals' everyday meaning-making practices with online digital data. Her research has explored how the collaborative, participatory digital environment supports the development of critical data literacies and how individuals come to understand data as a situated, socially constructed resource for meaning-making. She also studies the creation and interpretation of data visualization, exploring how everyday people understand their world through online, digital data. She is currently researching datafication, platform analytics, and learning assessment. She teaches classes in data literacies and collaborates with instructors across the University to assist them in developing quantitative reasoning and data literacies instruction.\

# Ellen Bledsoe

April 20, 11:20am -- Morning Panel, Data Science Training, Online ([room B](https://arizona.zoom.us/s/81289501438))

Ellen Bledsoe is an Assistant Professor of Practice in Ecological Data Science with SNRE. She is trained as a community ecologist, and it wasn't until graduate school that she heard about data science, let alone became interested in the field! After getting a PhD from the University of Florida, she spent a year as a postdoctoral teaching and research fellow for the Living Data Project, a Canada-wide data science training project for graduate students through the Canadian Institute for Ecology and Evolution. She teaches both undergraduate and graduate courses in data science and has published articles ranging from rodent community dynamics, inclusive pedagogy practices, and barriers to incorporating data science in undergraduate biology education.

# Sarah Bratt

April 20, 1:00pm -- Concurrent Afternoon Talk, Online ([room A](https://arizona.zoom.us/j/88420856384))

Dr. Sarah Bratt, PhD, is an Assistant Professor at the University of Arizona School of Information (iSchool). She holds a B.S. in Philosophy and M.S. in Library and Information Science with a Data Science certificate. Her research lies at the intersection of scholarly communication, research data management, and science of science. The overarching goal of her research is to understand and design for long-term research data sustainability and actionable science policy. Her research has been published in Quantitative Science Studies (QSS), Journal of Informetrics, and Scientometrics. She was a research Fellow at the Laboratory of Innovation Science at Harvard (LISH) and a Fellow at the iSchool Inclusion Institute (i3) and received multiple awards including the Masters' prize in Library & Information Science at Syracuse University and honorable mention as a 2022 Better Scientific Software (BSSw) Fellow.

# Charlotte Pearson

April 20, 1:00pm -- Concurrent Afternoon Talk, Online ([room B](https://arizona.zoom.us/s/81289501438))

Charlotte Pearson is an Associate Professor in the Laboratory of Tree-Ring Research, affiliated with both Anthropology and Geosciences at UArizona. Her research examines the interface of past human and environmental interactions by establishing secure and accurate chronologies. She is developing a specialist research and training facility for tree-ring and radiocarbon studies at UArizona. The new facility will offer dating of anything containing carbon from the last c.40 thousand years as well as producing multi-millennial time-series of data from tree-rings and other single year radiocarbon archives to explore solar output, atmospheric, biosphere, and oceanic interactions.

# Meaghan Wetherell

April 20, 1:25pm -- Concurrent Afternoon Talk, Online ([room A](https://arizona.zoom.us/j/88420856384))

Dr. Meaghan Wetherell is a paleontologist, science communicator, and data scientist. She holds a B.S. in Biology from Oregon State University and a PhD in Earth Sciences from University of Oregon. Her research interests lie mostly in older material (25 million years ago is pretty cool stuff) but she keeps getting tricked into doing fun math for all these Ice Age projects.

# Danielle Van Boxel

April 20, 1:25pm -- Concurrent Afternoon Talk, Online ([room B](https://arizona.zoom.us/s/81289501438))

Danielle Van Boxel is a third year Ph.D. student in Applied Math at the University of Arizona and Senior Data Scientist with the Rincon Research Corporation. She previously worked in government for a decade generating and analyzing statistics to discover anomalies and patterns in seemingly random data. Her current research focuses on Bayesian methods in ensemble machine learning. In her free time, Danielle enjoys bird watching, tabletop RPGs, and making math puns.

# Data Blitz

+---------------------+
| \                   |
| Valeria Pfeifer     |
|                     |
| Kathleen J. Kennedy |
|                     |
| Simona Merlini      |
|                     |
| Kapua Ioane         |
|                     |
| Bailie Wynbelt      |
|                     |
| Nimet Beyza Bozdag  |
+---------------------+
